import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./style.css';
const sb=createClient('https://utuigrbcxiihwobamcxx.supabase.co','sb_publishable_COC51VKRIxuzt4vf-zmZEA_YsT6t4NI');
const nav=['Dashboard','Students','Groups','Support','Payroll','Finance'];
function App(){const[session,setSession]=useState(null),[page,setPage]=useState('Dashboard'),[email,setEmail]=useState(''),[pw,setPw]=useState(''),[data,setData]=useState({}),[err,setErr]=useState('');
useEffect(()=>{sb.auth.getSession().then(x=>setSession(x.data.session));return sb.auth.onAuthStateChange((_,s)=>setSession(s)).data.subscription.unsubscribe},[]);
useEffect(()=>{if(!session)return;(async()=>{setErr('');try{let [s,g,l,t]=await Promise.all([sb.from('students').select('*').order('full_name'),sb.from('groups').select('*').order('name'),sb.from('lessons').select('*'),sb.from('support_calls').select('*')]);setData({students:s.data||[],groups:g.data||[],lessons:l.data||[],support:t.data||[]})}catch(e){setErr(e.message)}})()},[session,page]);
if(!session)return <main className="login"><section><h1>Academic Department OS</h1><p>Sign in to continue</p><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={pw} onChange={e=>setPw(e.target.value)}/><button onClick={async()=>{let x=await sb.auth.signInWithPassword({email,password:pw});if(x.error)setErr(x.error.message)}}>Sign in</button><small>{err}</small></section></main>;
return <div className="app"><aside><h2>Academic OS</h2>{nav.map(n=><button className={page===n?'on':''} onClick={()=>setPage(n)}>{n}</button>)}<button onClick={()=>sb.auth.signOut()}>Sign out</button></aside><main><header><h1>{page}</h1></header>{err&&<div className="error">{err}</div>}<Page page={page} d={data} refresh={()=>setPage(x=>x)}/></main></div>}
function Page({page,d}){if(page==='Dashboard')return <><div className="cards"><Card n={d.students?.length||0} t="Students"/><Card n={d.groups?.filter(x=>x.active!==false).length||0} t="Groups"/><Card n={d.lessons?.length||0} t="Lessons"/><Card n={d.support?.length||0} t="Support records"/></div><h3>Operations overview</h3><p>Use Students and Groups to manage daily academic operations.</p></>;
if(page==='Students')return <Table heads={['Name','Phone','Status','Joined','Left / Status Date','Reason']} rows={(d.students||[]).map(x=>[x.full_name||x.name,x.phone,x.status,x.joined_at,x.left_at||x.status_changed_at,x.status_comment])}/>;
if(page==='Groups')return <><p className="hint">Each group has direct academic-sheet and lesson actions.</p><Table heads={['Group','Start date','Actions']} rows={(d.groups||[]).map(x=>[x.name,x.start_date,<span><button onClick={()=>alert('Academic Sheet: '+x.name)}>Open Sheet</button> <button onClick={()=>alert('Add Lesson: '+x.name)}>+ Add Lesson</button></span>])}/></>;
if(page==='Support')return <Table heads={['Student','Contact','Attendance reason','Homework reason','Note']} rows={(d.support||[]).map(x=>[x.student_id,x.contact_status,x.attendance_reason,x.homework_reason,x.note])}/>;
return <section className="panel"><h2>{page}</h2><p>This section is connected to the existing Academic Department database and will use the approved workflow.</p></section>}
function Card({n,t}){return <div className="card"><b>{n}</b><span>{t}</span></div>}function Table({heads,rows}){return <div className="table"><table><thead><tr>{heads.map(h=><th>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v??'—'}</td>)}</tr>)}</tbody></table></div>}createRoot(document.getElementById('root')).render(<App/>);